baseURL = "https://www.capitalmesh.net/"
languageCode = "en-us"
title = "Capital Region Mesh"

[module]

[[module.imports]]
path = "github.com/adityatelange/hugo-PaperMod"

[[module.imports]]
path = "github.com/hugomods/icons/vendors/bootstrap"

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowBreadCrumbs = false
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true
  mainSections = []

[params.icons.bootstrap]
enabled = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"

[permalinks]
  tags = "/blog/tags/:slug/"

[caches]
  [caches.images]
    dir = ':cacheDir/images'
    
[menu]
  [[menu.main]]
    name = "What is the Mesh?"
    url = "/what-is-the mesh/"
    weight = 1

  [[menu.main]]
    name = "Join"
    url = "/join/"
    weight = 2

  [[menu.main]]
    name = "Contribute"
    url = "/contribute/"
    weight = 3

  [[menu.main]]
    name = "Mission"
    url = "/mission/"
    weight = 4

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 50

