baseURL = "https://www.capitalmesh.net"
languageCode = "en-us"
title = "Capital Region Mesh"

[module]
[[module.imports]]
path = "github.com/adityatelange/hugo-PaperMod"

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = false
  ShowBreadCrumbs = false
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

[menu]
  [[menu.main]]
    name = "Mission"
    url = "/mission/"
    weight = 1

  [[menu.main]]
    name = "Join"
    url = "/join/"
    weight = 2

  [[menu.main]]
    name = "Contribute"
    url = "/contribute/"
    weight = 3

  [[menu.main]]
    name = "What is Meshtastic?"
    url = "/what-is-meshtastic/"
    weight = 4
