baseURL = "https://www.capitalmesh.net"
languageCode = "en-us"
title = "Capital Region Mesh"

[module]
[[module.imports]]
path = "github.com/adityatelange/hugo-PaperMod"

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = false
  ShowShareButtons = true
  ShowBreadCrumbs = false
  ShowPostNavLinks = true
  ShowCodeCopyButtons = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Mission"
    url = "/mission/"
    weight = 4

  [[menu.main]]
    name = "Join"
    url = "/join/"
    weight = 2

  [[menu.main]]
    name = "Contribute"
    url = "/contribute/"
    weight = 3

  [[menu.main]]
    name = "What is the Mesh?"
    url = "/what-is-the mesh/"
    weight = 1
