baseURL = 'https://www.capitalmesh.net'
languageCode = 'en-us'
title = 'CapitalMesh'
theme = "bootstrap"

[menu]
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Join"
    url = "/join/"
    weight = 2
